# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.14
      uses: actions/setup-python@v3
      with:
        python-version: "3.14"

    - name: Restore cache
      id: restoreCache
      uses: actions/cache/restore@v4
      with:
        path: |
          ./.numba_cache
        key: numba-${{ github.run_number }}
        restore-keys: |
          numba-${{ github.run_number - 1 }}

    - name: Huh
      continue-on-error: true
      run: |
        ls -la ./.numba_cache
        ls -la ./.numba_cache/*/
        python -m pickle ./.numba_cache/champs_v4_6eba136648b986623d42d8b93aeacb9d7f99f9e1/methods.compute_material_coefficients-9.py314.nbi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements_opt.txt
        sudo apt install ffmpeg
    - name: Test
      env:
        NUMBA_CACHE_DIR: ./.numba_cache
        NUMBA_DEBUG_CACHE: 1
      run: |
        python -m tests -f -g

    - name: Huhh
      continue-on-error: true
      run: |
        ls -la ./.numba_cache
        ls -la ./.numba_cache/*/
        python -m pickle ./.numba_cache/champs_v4_6eba136648b986623d42d8b93aeacb9d7f99f9e1/methods.compute_material_coefficients-9.py314.nbi
    
    # https://github.com/actions/cache/issues/342#issuecomment-2773231159
    - name: Save cache
      uses: actions/cache/save@v4
      id: saveCache
      # Save the cache even if build steps fail.
      if: always()
      with:
        key: numba-${{ github.run_number }}
        path: |
          ./.numba_cache
    - name: Delete old cache
      env:
        GH_TOKEN: ${{ github.token }}
      if: steps.restoreCache.outputs.cache-hit
      # Using `--repo` makes it so that this step doesn't require checking out the
      # repo first.
      run: gh cache delete --repo ${{ github.repository }} numba-${{ github.run_number - 1 }}
    
