# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache Numba
      id: cache-numba
      uses: actions/cache@v4
      with:
        path: |
          ./.numba_cache
        key: numba-${{ hashFiles('./.numba_cache/**/*') }}
        restore-keys: |
          numba-${{ hashFiles('./.numba_cache/**/*') }}
          numba-
    - name: Set up Python 3.14
      uses: actions/setup-python@v3
      with:
        python-version: "3.14"
    - name: Huh
      run: |
        ls -la ./.numba_cache
        ls -la ./.numba_cache/*/
        python -m pickle ./.numba_cache/champs_v4_6eba136648b986623d42d8b93aeacb9d7f99f9e1/methods.compute_material_coefficients-9.py314.nbi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements_opt.txt
        sudo apt install ffmpeg
    - name: Test
      env:
        NUMBA_CACHE_DIR: ./.numba_cache
        NUMBA_DEBUG_CACHE: 1
      run: |
        python -m tests -f -g
    - name: Huhh
      run: |
        ls -la ./.numba_cache
        ls -la ./.numba_cache/*/
        python -m pickle ./.numba_cache/champs_v4_6eba136648b986623d42d8b93aeacb9d7f99f9e1/methods.compute_material_coefficients-9.py314.nbi
    
